# Generated by Django 5.2 on 2025-04-14 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='description',
        ),
    ]
