# Generated by Django 5.2 on 2025-04-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogmodel_delete_blogpage'),
        ('user', '0002_remove_interest_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='blog_tags', to='user.interest'),
        ),
    ]
